### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by savvyzimmer** [DuckySoLucky/Vape-Lite#8]
Hello,

I'm getting some errors while trying to use this tool. 

The error I'm getting is this: 

Fail handler: websocketpp.transport.asio.socket:5 TLS handshake timed out
connection error 1
Fail handler: websocketpp.transport.asio.socket:5 TLS handshake timed out
connection error 2
![Uploading error.png…]()

**Comment by savvyzimmer** [comment]
This is also another part of the error that I forgot to include:

Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...31504, 0, 0))>) at C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...31504, 0, 0))>) at C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840>
Traceback (most recent call last):
  File "C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 847, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\bwz03\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by DuckySoLucky** [comment]
Hello, you do not have correct python installed

Contact me on Discord `DuckySoLucky#5181` for faster responses
